import type { Coach } from '../types/coach'
import type { Booking } from '../types/booking'

export const mockCoaches: Coach[] = [
  {
    id: '1',
    email: 'luca.veloci@example.com',
    firstName: 'Luca',
    lastName: 'Veloci',
    phone: '+39 333 1234567',
    role: 'coach',
    bio: 'Coach professionista con oltre 10 anni di esperienza nel padel. Ex giocatore professionista, ora dedico il mio tempo a formare la prossima generazione di campioni.',
    qualifications: ['FIP Livello 2', 'FIT Certificato', '10+ Anni Esperienza'],
    yearsExperience: 12,
    hourlyRate: 40,
    groupRate: 25,
    rating: 4.8,
    reviewCount: 127,
    isVerified: true,
    locations: [
      {
        id: 'loc1',
        name: 'Padel Club Cagliari',
        address: 'Via Roma 123, Cagliari',
        lat: 39.2238,
        lng: 9.1217,
      },
    ],
    availability: [
      { id: 'a1', dayOfWeek: 1, startTime: '09:00', endTime: '18:00' },
      { id: 'a2', dayOfWeek: 2, startTime: '09:00', endTime: '18:00' },
      { id: 'a3', dayOfWeek: 3, startTime: '10:00', endTime: '17:00' },
      { id: 'a4', dayOfWeek: 4, startTime: '09:00', endTime: '18:00' },
      { id: 'a5', dayOfWeek: 5, startTime: '09:00', endTime: '16:00' },
    ],
    lessonDurations: [60, 90],
    groupLessonsEnabled: true,
    groupSurcharge: 10,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'anna.serra@example.com',
    firstName: 'Anna',
    lastName: 'Serra',
    phone: '+39 333 7654321',
    role: 'coach',
    bio: 'Appassionata di padel da sempre, ho trasformato la mia passione in professione. Specializzata in lezioni per principianti e intermedi.',
    qualifications: ['FIP Livello 1', 'Istruttore CONI'],
    yearsExperience: 6,
    hourlyRate: 35,
    groupRate: 20,
    rating: 4.9,
    reviewCount: 89,
    isVerified: true,
    locations: [
      {
        id: 'loc2',
        name: 'Sporting Club Quartu',
        address: 'Via Dante 45, Quartu Sant\'Elena',
        lat: 39.2342,
        lng: 9.1821,
      },
    ],
    availability: [
      { id: 'a6', dayOfWeek: 1, startTime: '08:00', endTime: '14:00' },
      { id: 'a7', dayOfWeek: 3, startTime: '08:00', endTime: '14:00' },
      { id: 'a8', dayOfWeek: 5, startTime: '08:00', endTime: '14:00' },
    ],
    lessonDurations: [60, 90, 120],
    groupLessonsEnabled: true,
    groupSurcharge: 8,
    createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '3',
    email: 'marco.ferraro@example.com',
    firstName: 'Marco',
    lastName: 'Ferraro',
    phone: '+39 333 9998877',
    role: 'coach',
    bio: 'Ex campione regionale, offro lezioni ad alto livello per giocatori ambiziosi che vogliono competere in tornei.',
    qualifications: ['FIP Livello 3', 'Ex Professionista', 'Campione Regionale'],
    yearsExperience: 15,
    hourlyRate: 50,
    rating: 4.7,
    reviewCount: 203,
    isVerified: true,
    locations: [
      {
        id: 'loc3',
        name: 'Padel Arena Sardegna',
        address: 'Via Sardegna 78, Cagliari',
        lat: 39.2156,
        lng: 9.1134,
      },
    ],
    availability: [
      { id: 'a9', dayOfWeek: 2, startTime: '14:00', endTime: '20:00' },
      { id: 'a10', dayOfWeek: 4, startTime: '14:00', endTime: '20:00' },
      { id: 'a11', dayOfWeek: 6, startTime: '09:00', endTime: '13:00' },
    ],
    lessonDurations: [60, 90],
    groupLessonsEnabled: false,
    createdAt: '2023-11-01T00:00:00Z',
  },
  {
    id: '4',
    email: 'giulia.piras@example.com',
    firstName: 'Giulia',
    lastName: 'Piras',
    phone: '+39 333 5556677',
    role: 'coach',
    bio: 'Giovane coach emergente con un approccio moderno e divertente. Le mie lezioni combinano tecnica e gioco per massimo divertimento.',
    qualifications: ['FIP Livello 1', 'Laurea Scienze Motorie'],
    yearsExperience: 3,
    hourlyRate: 30,
    groupRate: 15,
    rating: 4.6,
    reviewCount: 42,
    isVerified: true,
    locations: [
      {
        id: 'loc4',
        name: 'Beach Padel Poetto',
        address: 'Lungomare Poetto, Cagliari',
        lat: 39.2051,
        lng: 9.1545,
      },
    ],
    availability: [
      { id: 'a12', dayOfWeek: 1, startTime: '16:00', endTime: '20:00' },
      { id: 'a13', dayOfWeek: 2, startTime: '16:00', endTime: '20:00' },
      { id: 'a14', dayOfWeek: 3, startTime: '16:00', endTime: '20:00' },
      { id: 'a15', dayOfWeek: 4, startTime: '16:00', endTime: '20:00' },
      { id: 'a16', dayOfWeek: 5, startTime: '16:00', endTime: '20:00' },
    ],
    lessonDurations: [60],
    groupLessonsEnabled: true,
    groupSurcharge: 5,
    createdAt: '2024-06-01T00:00:00Z',
  },
]

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    code: 'PH-2024-001234',
    coachId: '1',
    coachName: 'Luca Veloci',
    playerId: 'p1',
    playerName: 'Alessandro Bianchi',
    date: '2024-01-20',
    startTime: '10:00',
    endTime: '11:00',
    duration: 60,
    type: 'single',
    location: 'Padel Club Cagliari',
    courtName: 'Campo 2',
    status: 'confirmed',
    price: 40,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'b2',
    code: 'PH-2024-001235',
    coachId: '2',
    coachName: 'Anna Serra',
    playerId: 'p1',
    playerName: 'Sofia Conti',
    date: '2024-01-22',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    type: 'group',
    location: 'Sporting Club Quartu',
    courtName: 'Campo 1',
    status: 'confirmed',
    price: 25,
    participants: [
      { id: 'pp1', name: 'Marco R.' },
      { id: 'pp2', name: 'Giulia B.' },
    ],
    createdAt: '2024-01-18T14:00:00Z',
  },
  {
    id: 'b3',
    code: 'PH-2024-001236',
    coachId: '3',
    coachName: 'Marco Ferraro',
    playerId: 'p1',
    playerName: 'Luca Romano',
    date: '2024-01-15',
    startTime: '16:00',
    endTime: '17:30',
    duration: 90,
    type: 'single',
    location: 'Padel Arena Sardegna',
    courtName: 'Campo 3',
    status: 'completed',
    price: 75,
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'b4',
    code: 'PH-2024-001237',
    coachId: '1',
    coachName: 'Luca Veloci',
    playerId: 'p1',
    playerName: 'Alessia Mura',
    date: '2024-01-18',
    startTime: '11:00',
    endTime: '12:00',
    duration: 60,
    type: 'single',
    location: 'Padel Club Cagliari',
    courtName: 'Campo 1',
    status: 'cancelled',
    price: 40,
    createdAt: '2024-01-12T11:00:00Z',
  },
  {
    id: 'b5',
    code: 'PH-2024-001238',
    coachId: '4',
    coachName: 'Giulia Piras',
    playerId: 'p1',
    playerName: 'Marco Villa',
    date: '2024-01-25',
    startTime: '17:00',
    endTime: '18:00',
    duration: 60,
    type: 'group',
    location: 'Beach Padel Poetto',
    status: 'pending',
    price: 30,
    participants: [
      { id: 'pp3', name: 'Andrea S.' },
    ],
    createdAt: '2024-01-20T15:00:00Z',
  },
]
